Promise.reject("Error occured").catch(err=>console.log(err));



// output : Error occured;